Added new sets and rebased
nhs-r-community/NHSRdatasets pull request #32
Opened 2021-03-05 21:24 UTC by StatsGary

Sorted out issues and rebased. @tomjemmett can you kindly have a look at next week and get these on.

2021-03-05 22:19 UTC, tomjemmett requested changes
the requestsed changes should solve issues with R cmd check. Make sure to run devtools::document to fix documentation

2021-03-05 22:19 UTC, tomjemmett commented on vignettes/stranded_model.Rmd
> +  select(everything(), -c(admit_date))
this is failing - I think there is a conflict on select with dplyr::select being masked. Need to fully qualify all calls to select throughout this Rmd

2021-03-05 22:19 UTC, tomjemmett commented on vignettes/stranded_model.Rmd
> +  %\VignetteIndexEntry{LOS_model: A simulated hospital length-of-stay dataset}
This title needs to be updated - causing vignette builds to gail

2021-03-05 22:19 UTC, tomjemmett commented on R/synthetic_news_data.R
> +
this space needs to be removed

2021-03-05 22:19 UTC, tomjemmett commented on R/synthetic_news_data.R
> +#' Synthetic NEWS data(\href{https://www.rcplondon.ac.uk/projects/outputs/national-early-warning-score-news-2}) as the results of the NHSR_synpop package.
\href{} is not necessary as vignettes are rendered with markdown - this will remove formatting warning in Rcmd check

2021-03-05 22:26 UTC, StatsGary commented
Thanks Tom. Will look and fix tomorrow.

2021-03-05 23:19 UTC, tomjemmett commented
Cheers, sorry for the pedantry, but cran will moan otherwise! 🙂

2021-03-05 23:23 UTC, StatsGary commented
No mate. I know how CRAN can be pal. Thanks bud ☺️

2021-03-06 02:05 UTC, StatsGary commented
@tomjemmett checked that all checks have passed on Travis CI and is looking good. The issue was two packages needed to be bought in, so added to DESCRIPTION file.

2021-03-06 22:20 UTC, tomjemmett approved these changes

2021-03-08 16:32 UTC, merged

2021-03-08 16:33 UTC, chrismainey commented
Good form @StatsGary .  Will try and get submitted to CRAN asap.

2021-03-08 16:49 UTC, StatsGary commented
Cheers team CRAN 😁

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Chris Mainey <notifications@github.com>
Sent: Monday, March 8, 2021 4:33:36 PM
To: nhs-r-community/NHSRdatasets <NHSRdatasets@noreply.github.com>
Cc: Gary Hutson <gary.hutson.uk@hotmail.co.uk>; Mention <mention@noreply.github.com>
Subject: Re: [nhs-r-community/NHSRdatasets] Added new sets and rebased (#32)


Good form @StatsGary<https://github.com/StatsGary> . Will try and get submitted to CRAN asap.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/nhs-r-community/NHSRdatasets/pull/32#issuecomment-792881517>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKP4BOE5PPCONGQ37ZLPVB3TCT36BANCNFSM4YV5GWMQ>.