Update readme
nhs-r-community/NHSRdatasets pull request #57
Opened 2023-07-12 19:09 UTC by Lextuga007

2023-07-17 09:13 UTC, tomjemmett requested changes

2023-07-17 09:13 UTC, tomjemmett commented on README.Rmd
> +>>>>>>> 87800e0b30f9343e0d00493ca9daf6040c72790e
should this line be deleted?

2023-07-17 09:13 UTC, tomjemmett commented on README.Rmd
> +You can install the [CRAN](https://CRAN.R-project.org) with:
should this be

> You can install the package from CRAN

2023-07-17 09:13 UTC, tomjemmett commented on README.Rmd
> +To install the development version from [GitHub](https://github.com/) use:
change use to with

2023-07-18 20:10 UTC, tomjemmett requested changes
spotted what looks like a duplicated line, but that may be because I'm viewing on mobile. minor pedantic point, but looks like previously we used "packages" and have continued that, when it should be "package". the point about how to cite the package could become a new issue to solve later

2023-07-19 17:19 UTC, Lextuga007 commented on README.Rmd
> +Please cite the use of {NHSRdatasets} and promote the work of the NHS-R
Good question, I'll look into it.

2023-07-19 17:21 UTC, Lextuga007 commented on README.Rmd
> +Please cite the use of {NHSRdatasets} and promote the work of the NHS-R
https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/ gives details. I'm not sure it's necessary, we don't cite the use of many packages but I'll leave the request to promote as that's kind of what we want 😄

2023-07-19 19:44 UTC, tomjemmett reviewed
Has readme been re-rendered?

2023-07-28 21:24 UTC, merged